# Generated by Django 3.2.9 on 2021-11-11 18:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_dialogue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dialogue',
            new_name='Dialog',
        ),
    ]
