# Generated by Django 3.2.9 on 2021-11-11 19:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_rename_dialogue_dialog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dialog',
            unique_together={('initiator', 'answerer')},
        ),
    ]
