# Generated by Django 3.2.9 on 2021-11-14 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_dialog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
