# Generated by Django 3.2.9 on 2021-11-14 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_dialog_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='created',
        ),
        migrations.AddField(
            model_name='dialog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Момент создания диалога'),
            preserve_default=False,
        ),
    ]
