# Generated by Django 3.2.9 on 2021-11-14 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_auto_20211114_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Момент отправки сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('-sent_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='dialog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Диалог', 'verbose_name_plural': 'Диалоги'},
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='dialogmessage',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.dialog', verbose_name='Диалог'),
        ),
        migrations.AddField(
            model_name='dialogmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения'),
        ),
    ]
