# Generated by Django 3.2.9 on 2021-11-19 09:44

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_auto_20211114_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Момент создания группы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(related_name='chat_groups', through='chat.ChatGroupMember', to=settings.AUTH_USER_MODEL, verbose_name='Участники группы'),
        ),
        migrations.AddField(
            model_name='chatgroupmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Момент присоединения к группе'),
            preserve_default=False,
        ),
    ]
