# Generated by Django 3.2.9 on 2021-11-19 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20211119_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название группы'),
        ),
    ]
