# Generated by Django 3.2.9 on 2021-11-19 10:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0010_alter_chatgroup_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatgroup',
            unique_together={('title', 'creator')},
        ),
    ]
