# Generated by Django 3.2.9 on 2021-11-19 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0011_alter_chatgroup_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogmessage',
            options={'ordering': ('-sent_at',), 'verbose_name': 'Сообщение диалогов', 'verbose_name_plural': 'Сообщения диалогов'},
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Момент отправки сообщения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatgroup', verbose_name='Группа')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение групп',
                'verbose_name_plural': 'Сообщения групп',
                'ordering': ('-sent_at',),
                'abstract': False,
            },
        ),
    ]
