# Generated by Django 3.2.9 on 2021-11-30 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0013_auto_20211130_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='dialogmessage',
            name='users_that_read',
            field=models.ManyToManyField(related_name='read_dialog_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи прочитавшие сообщение'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='users_that_read',
            field=models.ManyToManyField(related_name='read_group_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи прочитавшие сообщение'),
        ),
    ]
